
from support.ApiRepositories.MockupApiRepository import MockupApiRepository
from support.CacheRepositories.MemoryCacheRepository import MemoryCacheRepository


CACH_REPOSITORY=MemoryCacheRepository(token=None)
API_REPOSITORY=MockupApiRepository()